version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: Install libmilter
          command: |
            apt-get update
            apt-get install libmilter-dev
      - run:
          name: Configure
          command: |
            sh autoconf.sh.in
            ./configure
      - run:
          name: Build
          command: |
            make all
